AWSTemplateFormatVersion: "2010-09-09"
Description: 3 Node Cluster in a VPC with a Network Load balancer to host our kubernetes application

Parameters:

Resources:
  PlacementGroup:
  Type: AWS::EC2::PlacementGroup
  Description: Cluster placement groups lower inter-node network latency on AWS
  Properties: 
    Strategy: cluster

Outputs: